### ISSUE TITLE
"TypeError: Converting circular structure to JSON" using example

### ISSUE THREAD

**Issue by j2l** [rgstephens/node-red-contrib-graphql#1] opened 2018-06-28 14:45 UTC
Looks great! 
But on Node-Red 0.18.7, I get 
![image](https://user-images.githubusercontent.com/65325/42041268-ddb40620-7af1-11e8-9f89-04856588253f.png)

I tried to query the website https://developer.deutschebahn.com/free1bahnql/graphql directly and it worked. I know that the server replies.

I also tried with another graphql query and get the same result:
![image](https://user-images.githubusercontent.com/65325/42041475-4d7cf75a-7af2-11e8-9bab-6200de20875c.png)

**Comment by rgstephens** [comment] 2018-07-10 21:30
@j2l Thanks for reporting this.  I'm on v0.16.2.  I'll upgrade and try to duplicate.

**Comment by rgstephens** [comment] 2018-07-11 03:03
I upgraded Node Red to 0.18.7 but still couldn't duplicate the problem. However, I just pushed an update (0.2.3) which should address any issues with the circular JSON error.  Please upgrade and let me know if you still encounter the problem.

**Comment by rgstephens** [comment] 2018-07-31 00:13
Closing this item. Can re-open if the problem is encountered again under v0.2.3.

**Closed by rgstephens** 2018-07-31 00:13 UTC
